// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgD5XRXyK2_RP7LGXNXHrpqimyHtUIT4s',
    appId: '1:450745776806:android:0c75ea54203fd2c32f5267',
    messagingSenderId: '450745776806',
    projectId: 'chess-339807',
    storageBucket: 'chess-339807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbkP1rbDh4uE3Woi2-nbB459SBm_WZGpw',
    appId: '1:450745776806:ios:07db0e1e43236a992f5267',
    messagingSenderId: '450745776806',
    projectId: 'chess-339807',
    storageBucket: 'chess-339807.appspot.com',
    androidClientId:
        '450745776806-97hpfrldk1b9j6geaf6sp24reqa0qavb.apps.googleusercontent.com',
    iosClientId:
        '450745776806-t8lpbko8vhrn7kigsuhmk4n7en8let67.apps.googleusercontent.com',
    iosBundleId: 'com.example.chess',
  );
}
